# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "colorize"

gem "rspec", "~> 3.10"

gem "terminal-table"

gem "pry-byebug", "~> 3.4"

gem "brakeman", "~> 3.3", ">= 3.3.2"

gem 'tty-prompt', '~> 0.23.1'